project_info:
  name: "Manufacturing Resource Allocation Optimization"
  version: "1.0.0"
  description: "GA and MIP optimization for manufacturing resource allocation"

data_settings:
  or_library_file: "mknapcb1.txt"
  target_products: 100
  target_constraints: 5
  company_name: "TechParts Manufacturing Corporation"
  planning_period: "Q1 2025"
  data_directory: "manufacturing_data"
  problem_instance_name: "manufacturing_problem_1"

ga_parameters:
  hyperparameter_tuning:
    population_sizes: [50, 100, 150]
    mutation_rates: [0.01, 0.02, 0.05]
    crossover_rates: [0.7, 0.8, 0.9]
    generations_list: [100, 200]
  
  default_parameters:
    population_size: 100
    generations: 200
    crossover_rate: 0.8
    mutation_rate: 0.01
    tournament_size: 3

mip_parameters:
  solver_name: "CBC"
  time_limit_seconds: 300
  verbose: true